version: "3.8"

services:
  app-scrapper:
    container_name: app-scrapper
    build:
      context: services/app-scrapper
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=${PORT}
    healthcheck:
      test: ping -c3 ah_network:${STREAMER_PORT}
      interval: 10s
      retries: 10
  app-gateway:
    container_name: app-gateway
    build:
      context: services/app-gateway
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=${PORT}
    healthcheck:
      test: ping -c3 ah_network:${STREAMER_PORT}
      interval: 10s
      retries: 10

  app-notifications:
    container_name: app-notifications
    build:
      context: services/app-notifications
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=${PORT}
    healthcheck:
      test: ping -c3 ah_network:${STREAMER_PORT}
      interval: 10s
      retries: 10


  mock-server-v1:
    container_name: mock-server-v1
    build:
      context: docs
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=${PORT}
    healthcheck:
      test: ping -c3 ah_network:${STREAMER_PORT}
      interval: 10s
      retries: 10
    volumes:
      - ./api-v1-docs.yaml:/usr/src/prism/packages/cli/api-v1-docs.yaml


  # Third party services
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - keniapowervol:/data/db


volumes:
  keniapowervol:
    driver: local