# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from notifications import notifications_pb2 as notifications_dot_notifications__pb2


class NotificationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSubscriber = channel.unary_unary(
                '/Notifications/AddSubscriber',
                request_serializer=notifications_dot_notifications__pb2.Subscriber.SerializeToString,
                response_deserializer=notifications_dot_notifications__pb2.Response.FromString,
                )
        self.Unsubscribe = channel.unary_unary(
                '/Notifications/Unsubscribe',
                request_serializer=notifications_dot_notifications__pb2.SubscriptionID.SerializeToString,
                response_deserializer=notifications_dot_notifications__pb2.Response.FromString,
                )


class NotificationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddSubscriber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSubscriber': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSubscriber,
                    request_deserializer=notifications_dot_notifications__pb2.Subscriber.FromString,
                    response_serializer=notifications_dot_notifications__pb2.Response.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=notifications_dot_notifications__pb2.SubscriptionID.FromString,
                    response_serializer=notifications_dot_notifications__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Notifications', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Notifications(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddSubscriber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Notifications/AddSubscriber',
            notifications_dot_notifications__pb2.Subscriber.SerializeToString,
            notifications_dot_notifications__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Notifications/Unsubscribe',
            notifications_dot_notifications__pb2.SubscriptionID.SerializeToString,
            notifications_dot_notifications__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
