# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications/notifications.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!notifications/notifications.proto\";\n\nSubscriber\x12\r\n\x05\x45mail\x18\x01 \x01(\t\x12\x0e\n\x06Region\x18\x02 \x01(\t\x12\x0e\n\x06\x43ounty\x18\x03 \x01(\t\"\x1e\n\x0eSubscriptionID\x12\x0c\n\x04UUID\x18\x01 \x01(\t\"8\n\x08Response\x12\x0f\n\x07Message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x32\x63\n\rNotifications\x12\'\n\rAddSubscriber\x12\x0b.Subscriber\x1a\t.Response\x12)\n\x0bUnsubscribe\x12\x0f.SubscriptionID\x1a\t.ResponseB?Z=github.com/oyamo/kplc-outage-microservice/proto/notificationsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifications.notifications_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z=github.com/oyamo/kplc-outage-microservice/proto/notifications'
  _SUBSCRIBER._serialized_start=37
  _SUBSCRIBER._serialized_end=96
  _SUBSCRIPTIONID._serialized_start=98
  _SUBSCRIPTIONID._serialized_end=128
  _RESPONSE._serialized_start=130
  _RESPONSE._serialized_end=186
  _NOTIFICATIONS._serialized_start=188
  _NOTIFICATIONS._serialized_end=287
# @@protoc_insertion_point(module_scope)
