// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: proto/power.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat  float32 `protobuf:"fixed32,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Long float32 `protobuf:"fixed32,2,opt,name=Long,proto3" json:"Long,omitempty"`
}

func (x *Cordinate) Reset() {
	*x = Cordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_power_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cordinate) ProtoMessage() {}

func (x *Cordinate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_power_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cordinate.ProtoReflect.Descriptor instead.
func (*Cordinate) Descriptor() ([]byte, []int) {
	return file_proto_power_proto_rawDescGZIP(), []int{0}
}

func (x *Cordinate) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Cordinate) GetLong() float32 {
	if x != nil {
		return x.Long
	}
	return 0
}

type LocationsUnderCords struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	County string   `protobuf:"bytes,1,opt,name=County,proto3" json:"County,omitempty"`
	Area   string   `protobuf:"bytes,2,opt,name=Area,proto3" json:"Area,omitempty"`
	Towns  []string `protobuf:"bytes,3,rep,name=towns,proto3" json:"towns,omitempty"`
}

func (x *LocationsUnderCords) Reset() {
	*x = LocationsUnderCords{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_power_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocationsUnderCords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationsUnderCords) ProtoMessage() {}

func (x *LocationsUnderCords) ProtoReflect() protoreflect.Message {
	mi := &file_proto_power_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationsUnderCords.ProtoReflect.Descriptor instead.
func (*LocationsUnderCords) Descriptor() ([]byte, []int) {
	return file_proto_power_proto_rawDescGZIP(), []int{1}
}

func (x *LocationsUnderCords) GetCounty() string {
	if x != nil {
		return x.County
	}
	return ""
}

func (x *LocationsUnderCords) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *LocationsUnderCords) GetTowns() []string {
	if x != nil {
		return x.Towns
	}
	return nil
}

type Customer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name    string  `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email   string  `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Address string  `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	Lat     float32 `protobuf:"fixed32,5,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Long    float32 `protobuf:"fixed32,6,opt,name=Long,proto3" json:"Long,omitempty"`
}

func (x *Customer) Reset() {
	*x = Customer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_power_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_power_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_proto_power_proto_rawDescGZIP(), []int{2}
}

func (x *Customer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Customer) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Customer) GetLong() float32 {
	if x != nil {
		return x.Long
	}
	return 0
}

type CustomerId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *CustomerId) Reset() {
	*x = CustomerId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_power_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerId) ProtoMessage() {}

func (x *CustomerId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_power_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerId.ProtoReflect.Descriptor instead.
func (*CustomerId) Descriptor() ([]byte, []int) {
	return file_proto_power_proto_rawDescGZIP(), []int{3}
}

func (x *CustomerId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_power_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_power_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_power_proto_rawDescGZIP(), []int{4}
}

func (x *UnsubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnsubscribeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Outage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date      string   `protobuf:"bytes,1,opt,name=Date,proto3" json:"Date,omitempty"`
	TimeStart string   `protobuf:"bytes,2,opt,name=TimeStart,proto3" json:"TimeStart,omitempty"`
	TimeEnd   string   `protobuf:"bytes,3,opt,name=TimeEnd,proto3" json:"TimeEnd,omitempty"`
	Area      string   `protobuf:"bytes,5,opt,name=Area,proto3" json:"Area,omitempty"`
	County    string   `protobuf:"bytes,6,opt,name=County,proto3" json:"County,omitempty"`
	Region    string   `protobuf:"bytes,7,opt,name=Region,proto3" json:"Region,omitempty"`
	Towns     []string `protobuf:"bytes,4,rep,name=towns,proto3" json:"towns,omitempty"`
}

func (x *Outage) Reset() {
	*x = Outage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_power_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outage) ProtoMessage() {}

func (x *Outage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_power_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outage.ProtoReflect.Descriptor instead.
func (*Outage) Descriptor() ([]byte, []int) {
	return file_proto_power_proto_rawDescGZIP(), []int{5}
}

func (x *Outage) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Outage) GetTimeStart() string {
	if x != nil {
		return x.TimeStart
	}
	return ""
}

func (x *Outage) GetTimeEnd() string {
	if x != nil {
		return x.TimeEnd
	}
	return ""
}

func (x *Outage) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *Outage) GetCounty() string {
	if x != nil {
		return x.County
	}
	return ""
}

func (x *Outage) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Outage) GetTowns() []string {
	if x != nil {
		return x.Towns
	}
	return nil
}

type OutageFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date      string  `protobuf:"bytes,1,opt,name=Date,proto3" json:"Date,omitempty"`
	TimeStart string  `protobuf:"bytes,2,opt,name=TimeStart,proto3" json:"TimeStart,omitempty"`
	TimeEnd   string  `protobuf:"bytes,3,opt,name=TimeEnd,proto3" json:"TimeEnd,omitempty"`
	DateStart string  `protobuf:"bytes,4,opt,name=DateStart,proto3" json:"DateStart,omitempty"`
	DateEnd   string  `protobuf:"bytes,5,opt,name=DateEnd,proto3" json:"DateEnd,omitempty"`
	Lat       float32 `protobuf:"fixed32,6,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Long      float32 `protobuf:"fixed32,7,opt,name=Long,proto3" json:"Long,omitempty"`
	Town      string  `protobuf:"bytes,8,opt,name=Town,proto3" json:"Town,omitempty"`
	County    string  `protobuf:"bytes,9,opt,name=County,proto3" json:"County,omitempty"`
	Area      string  `protobuf:"bytes,10,opt,name=Area,proto3" json:"Area,omitempty"`
	Region    string  `protobuf:"bytes,11,opt,name=Region,proto3" json:"Region,omitempty"`
}

func (x *OutageFilter) Reset() {
	*x = OutageFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_power_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutageFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutageFilter) ProtoMessage() {}

func (x *OutageFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_power_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutageFilter.ProtoReflect.Descriptor instead.
func (*OutageFilter) Descriptor() ([]byte, []int) {
	return file_proto_power_proto_rawDescGZIP(), []int{6}
}

func (x *OutageFilter) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *OutageFilter) GetTimeStart() string {
	if x != nil {
		return x.TimeStart
	}
	return ""
}

func (x *OutageFilter) GetTimeEnd() string {
	if x != nil {
		return x.TimeEnd
	}
	return ""
}

func (x *OutageFilter) GetDateStart() string {
	if x != nil {
		return x.DateStart
	}
	return ""
}

func (x *OutageFilter) GetDateEnd() string {
	if x != nil {
		return x.DateEnd
	}
	return ""
}

func (x *OutageFilter) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *OutageFilter) GetLong() float32 {
	if x != nil {
		return x.Long
	}
	return 0
}

func (x *OutageFilter) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *OutageFilter) GetCounty() string {
	if x != nil {
		return x.County
	}
	return ""
}

func (x *OutageFilter) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *OutageFilter) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type OutageFilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OutageFilterResponse) Reset() {
	*x = OutageFilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_power_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutageFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutageFilterResponse) ProtoMessage() {}

func (x *OutageFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_power_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutageFilterResponse.ProtoReflect.Descriptor instead.
func (*OutageFilterResponse) Descriptor() ([]byte, []int) {
	return file_proto_power_proto_rawDescGZIP(), []int{7}
}

var File_proto_power_proto protoreflect.FileDescriptor

var file_proto_power_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x09, 0x43, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x4c,
	0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x4c, 0x6f, 0x6e, 0x67, 0x22, 0x57, 0x0a, 0x13, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x72, 0x65, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x77,
	0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x77, 0x6e, 0x73, 0x22,
	0x84, 0x01, 0x0a, 0x08, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x4c,
	0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x4c, 0x6f, 0x6e, 0x67, 0x22, 0x1c, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x13, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xae, 0x01, 0x0a, 0x06,
	0x4f, 0x75, 0x74, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65,
	0x45, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x45,
	0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x41, 0x72, 0x65, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x77, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x77, 0x6e, 0x73, 0x22, 0x90, 0x02, 0x0a,
	0x0c, 0x4f, 0x75, 0x74, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x61, 0x74,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x44, 0x61,
	0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x65, 0x45,
	0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x44, 0x61, 0x74, 0x65, 0x45, 0x6e,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03,
	0x4c, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x04, 0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x6f, 0x77, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x6f, 0x77, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x41, 0x72, 0x65, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22,
	0x16, 0x0a, 0x14, 0x4f, 0x75, 0x74, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x73, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x09, 0x2e, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x1a, 0x09, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x12, 0x38, 0x0a, 0x13, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x0b, 0x2e, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x14, 0x2e, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x79, 0x0a, 0x09,
	0x53, 0x63, 0x72, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x35, 0x0a, 0x0d, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x61, 0x67, 0x65, 0x73, 0x12, 0x0d, 0x2e, 0x4f, 0x75, 0x74,
	0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x15, 0x2e, 0x4f, 0x75, 0x74, 0x61,
	0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x55, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0a, 0x2e, 0x43, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x1a, 0x14, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x55, 0x6e, 0x64,
	0x65, 0x72, 0x43, 0x6f, 0x72, 0x64, 0x73, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x79, 0x61, 0x6d, 0x6f, 0x2f, 0x6b, 0x70, 0x6c, 0x63,
	0x2d, 0x6f, 0x75, 0x74, 0x61, 0x67, 0x65, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_power_proto_rawDescOnce sync.Once
	file_proto_power_proto_rawDescData = file_proto_power_proto_rawDesc
)

func file_proto_power_proto_rawDescGZIP() []byte {
	file_proto_power_proto_rawDescOnce.Do(func() {
		file_proto_power_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_power_proto_rawDescData)
	})
	return file_proto_power_proto_rawDescData
}

var file_proto_power_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_power_proto_goTypes = []interface{}{
	(*Cordinate)(nil),            // 0: Cordinate
	(*LocationsUnderCords)(nil),  // 1: LocationsUnderCords
	(*Customer)(nil),             // 2: Customer
	(*CustomerId)(nil),           // 3: CustomerId
	(*UnsubscribeResponse)(nil),  // 4: UnsubscribeResponse
	(*Outage)(nil),               // 5: Outage
	(*OutageFilter)(nil),         // 6: OutageFilter
	(*OutageFilterResponse)(nil), // 7: OutageFilterResponse
}
var file_proto_power_proto_depIdxs = []int32{
	2, // 0: Notification.SubscribeCustomer:input_type -> Customer
	3, // 1: Notification.UnsubscribeCustomer:input_type -> CustomerId
	6, // 2: Scrapping.FilterOutages:input_type -> OutageFilter
	0, // 3: Scrapping.GetLocationsUnder:input_type -> Cordinate
	2, // 4: Notification.SubscribeCustomer:output_type -> Customer
	4, // 5: Notification.UnsubscribeCustomer:output_type -> UnsubscribeResponse
	7, // 6: Scrapping.FilterOutages:output_type -> OutageFilterResponse
	1, // 7: Scrapping.GetLocationsUnder:output_type -> LocationsUnderCords
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_power_proto_init() }
func file_proto_power_proto_init() {
	if File_proto_power_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_power_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_power_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocationsUnderCords); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_power_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Customer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_power_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_power_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_power_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_power_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutageFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_power_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutageFilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_power_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_power_proto_goTypes,
		DependencyIndexes: file_proto_power_proto_depIdxs,
		MessageInfos:      file_proto_power_proto_msgTypes,
	}.Build()
	File_proto_power_proto = out.File
	file_proto_power_proto_rawDesc = nil
	file_proto_power_proto_goTypes = nil
	file_proto_power_proto_depIdxs = nil
}
